configs:
  params:
    server.insecure: "true"

server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    controller: aws
    ingressClassName: alb
    hostname: argocd.lab-commit.internal
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      external-dns.alpha.kubernetes.io/hostname: argocd.lab-commit.internal
    aws:
      backendProtocolVersion: HTTP1
      serviceType: ClusterIP
