apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: {{ include "lab-commit.name" . }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.targetPort }}
